import { useState } from "react";
import { Expand } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { galleryImages } from "@/data/schoolData";
import { Section, SectionHeader } from "./Shared";
const categories = ["All", "Campus", "Classrooms", "Activities", "Sports", "Events"];
export function Gallery() {
  const [category, setCategory] = useState("All");
  const [selected, setSelected] = useState<(typeof galleryImages)[number] | null>(null);
  const shown = category === "All" ? galleryImages : galleryImages.filter(image => image.category === category);
  return <Section id="gallery"><SectionHeader eyebrow="A glimpse of school life" title="Image Gallery" text="These illustrative placeholders can be replaced with approved photographs from the school." /><div className="mt-8 flex flex-wrap justify-center gap-2" role="group" aria-label="Gallery categories">{categories.map(item => <Button key={item} variant={category === item ? "default" : "outline"} size="sm" onClick={() => setCategory(item)}>{item}</Button>)}</div><div className="mt-10 grid auto-rows-[210px] grid-cols-2 gap-3 md:auto-rows-[260px] md:grid-cols-4">{shown.map((image, index) => <button key={`${image.title}-${index}`} onClick={() => setSelected(image)} className={`group relative overflow-hidden text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ${index === 0 ? "col-span-2 row-span-2" : index === 3 ? "col-span-2" : ""}`}><img src={image.src} alt={image.title} width={1200} height={912} loading="lazy" className="size-full object-cover transition duration-500 group-hover:scale-105" style={{ objectPosition: image.position }} /><span className="absolute inset-0 bg-gallery-overlay opacity-70 transition group-hover:opacity-90" /><span className="absolute inset-x-0 bottom-0 flex items-end justify-between p-4 text-primary-foreground"><span><span className="block text-[10px] font-bold uppercase tracking-[0.18em] text-gold">{image.category}</span><span className="mt-1 block font-display text-base font-semibold sm:text-lg">{image.title}</span></span><Expand className="size-4" /></span></button>)}</div><Dialog open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)}><DialogContent className="max-w-5xl border-0 bg-primary p-2 text-primary-foreground sm:rounded-none">{selected && <><DialogTitle className="sr-only">{selected.title}</DialogTitle><DialogDescription className="sr-only">Expanded placeholder photograph in the {selected.category} category.</DialogDescription><img src={selected.src} alt={selected.title} width={1200} height={912} className="max-h-[80vh] w-full object-contain" /><div className="px-3 pb-2 pt-1"><span className="text-xs uppercase tracking-[0.18em] text-gold">{selected.category}</span><p className="font-display text-xl">{selected.title}</p></div></>}</DialogContent></Dialog></Section>;
}
